"""完善备注信息

Revision ID: 22627561d328
Revises: 7b0537205261
Create Date: 2019-12-07 21:37:18.035729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22627561d328'
down_revision = '7b0537205261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'about',
               existing_type=mysql.TEXT(),
               comment='关于',
               existing_nullable=True)
    op.alter_column('admins', 'blog_sub_title',
               existing_type=mysql.VARCHAR(length=100),
               comment='博客副标题',
               existing_nullable=True)
    op.alter_column('admins', 'blog_title',
               existing_type=mysql.VARCHAR(length=60),
               comment='博客标题',
               existing_nullable=True)
    op.alter_column('admins', 'name',
               existing_type=mysql.VARCHAR(length=30),
               comment='管理员姓名',
               existing_nullable=True)
    op.alter_column('admins', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               comment='密码',
               existing_nullable=True)
    op.alter_column('admins', 'username',
               existing_type=mysql.VARCHAR(length=20),
               comment='管理员用户名',
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(length=30),
               comment='分类名称',
               existing_nullable=True)
    op.alter_column('comments', 'author',
               existing_type=mysql.VARCHAR(length=30),
               comment='评论作者',
               existing_nullable=True)
    op.alter_column('comments', 'body',
               existing_type=mysql.TEXT(),
               comment='评论的内容',
               existing_nullable=True)
    op.alter_column('comments', 'email',
               existing_type=mysql.VARCHAR(length=254),
               comment='评论的邮箱地址',
               existing_nullable=True)
    op.alter_column('comments', 'from_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment='评论是否来自管理员',
               existing_nullable=True)
    op.alter_column('comments', 'reviewed',
               existing_type=mysql.TINYINT(display_width=1),
               comment='评论是否经过审核',
               existing_nullable=True)
    op.alter_column('comments', 'site',
               existing_type=mysql.VARCHAR(length=255),
               comment='评论的站点',
               existing_nullable=True)
    op.alter_column('comments', 'timestamp',
               existing_type=mysql.DATETIME(),
               comment='评论的创建时间',
               existing_nullable=True)
    op.alter_column('links', 'name',
               existing_type=mysql.VARCHAR(length=30),
               comment='链接名',
               existing_nullable=True)
    op.alter_column('links', 'url',
               existing_type=mysql.VARCHAR(length=255),
               comment='链接的url',
               existing_nullable=True)
    op.alter_column('posts', 'body',
               existing_type=mysql.TEXT(),
               comment='文章主体',
               existing_nullable=True)
    op.alter_column('posts', 'can_comment',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否可以评论',
               existing_nullable=True)
    op.alter_column('posts', 'slug',
               existing_type=mysql.VARCHAR(length=90),
               comment='固定链接',
               existing_nullable=True)
    op.alter_column('posts', 'timestamp',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
    op.alter_column('posts', 'title',
               existing_type=mysql.VARCHAR(length=60),
               comment='文章的标题',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
               existing_type=mysql.VARCHAR(length=60),
               comment=None,
               existing_comment='文章的标题',
               existing_nullable=True)
    op.alter_column('posts', 'timestamp',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
    op.alter_column('posts', 'slug',
               existing_type=mysql.VARCHAR(length=90),
               comment=None,
               existing_comment='固定链接',
               existing_nullable=True)
    op.alter_column('posts', 'can_comment',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否可以评论',
               existing_nullable=True)
    op.alter_column('posts', 'body',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='文章主体',
               existing_nullable=True)
    op.alter_column('links', 'url',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='链接的url',
               existing_nullable=True)
    op.alter_column('links', 'name',
               existing_type=mysql.VARCHAR(length=30),
               comment=None,
               existing_comment='链接名',
               existing_nullable=True)
    op.alter_column('comments', 'timestamp',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='评论的创建时间',
               existing_nullable=True)
    op.alter_column('comments', 'site',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='评论的站点',
               existing_nullable=True)
    op.alter_column('comments', 'reviewed',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='评论是否经过审核',
               existing_nullable=True)
    op.alter_column('comments', 'from_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='评论是否来自管理员',
               existing_nullable=True)
    op.alter_column('comments', 'email',
               existing_type=mysql.VARCHAR(length=254),
               comment=None,
               existing_comment='评论的邮箱地址',
               existing_nullable=True)
    op.alter_column('comments', 'body',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='评论的内容',
               existing_nullable=True)
    op.alter_column('comments', 'author',
               existing_type=mysql.VARCHAR(length=30),
               comment=None,
               existing_comment='评论作者',
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=mysql.VARCHAR(length=30),
               comment=None,
               existing_comment='分类名称',
               existing_nullable=True)
    op.alter_column('admins', 'username',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='管理员用户名',
               existing_nullable=True)
    op.alter_column('admins', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='密码',
               existing_nullable=True)
    op.alter_column('admins', 'name',
               existing_type=mysql.VARCHAR(length=30),
               comment=None,
               existing_comment='管理员姓名',
               existing_nullable=True)
    op.alter_column('admins', 'blog_title',
               existing_type=mysql.VARCHAR(length=60),
               comment=None,
               existing_comment='博客标题',
               existing_nullable=True)
    op.alter_column('admins', 'blog_sub_title',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='博客副标题',
               existing_nullable=True)
    op.alter_column('admins', 'about',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='关于',
               existing_nullable=True)
    # ### end Alembic commands ###
