"""文章能否评论添加默认值

Revision ID: 611919b26b39
Revises: 22627561d328
Create Date: 2019-12-17 20:08:30.379139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '611919b26b39'
down_revision = '22627561d328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'can_comment',
               existing_type=mysql.TINYINT(display_width=1),
               comment='可以评论',
               existing_comment='是否可以评论',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'can_comment',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否可以评论',
               existing_comment='可以评论',
               existing_nullable=True)
    # ### end Alembic commands ###
