"""Post模型类增加slug字段

Revision ID: 7b0537205261
Revises: 
Create Date: 2019-12-07 21:26:31.641230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0537205261'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['name'])
    op.add_column('posts', sa.Column('slug', sa.String(length=90), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'slug')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
