"""增加是否确认字段

Revision ID: a745cf195f68
Revises: 611919b26b39
Create Date: 2019-12-23 17:18:13.322059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a745cf195f68'
down_revision = '611919b26b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('comfirmed', sa.Boolean(), nullable=True, comment='是否确认'))
    op.add_column('admins', sa.Column('email', sa.String(length=40), nullable=True, comment='邮箱地址'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'email')
    op.drop_column('admins', 'comfirmed')
    # ### end Alembic commands ###
