"""增加头像字段

Revision ID: f9b1143acd89
Revises: 73eb6f55eb9c
Create Date: 2019-12-26 15:04:36.654188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b1143acd89'
down_revision = '73eb6f55eb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('avatar_l', sa.String(length=64), nullable=True))
    op.add_column('admins', sa.Column('avatar_m', sa.String(length=64), nullable=True))
    op.add_column('admins', sa.Column('avatar_raw', sa.String(length=64), nullable=True))
    op.add_column('admins', sa.Column('avatar_s', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'avatar_s')
    op.drop_column('admins', 'avatar_raw')
    op.drop_column('admins', 'avatar_m')
    op.drop_column('admins', 'avatar_l')
    # ### end Alembic commands ###
